;***************************************************************
;HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
;***************************************************************
;**********************   F A B S     **************************
;***************************************************************
	.TITLE FABS
        .RADIX	8
	
	.IDENT /V1.0/

	.PSECT .SFUN.

FABS::	SETD
	ABSF	R0
	RTS	PC
	
	.END
                
